export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const API_REQUEST_STARTED = "API_REQUEST_STARTED";
export const API_REQUEST_SUCCESS = "API_REQUEST_SUCCESS";
export const API_REQUEST_FAILURE = "API_REQUEST_FAILURE";

export const ADD_ACCESS_TOKEN = "ADD_ACCESS_TOKEN";
export const REMOVE_ACCESS_TOKEN = "REMOVE_ACCESS_TOKEN";

export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const REMOVE_USER = "REMOVE_USER";
export const ADD_AGENTTYPE = "ADD_AGENTTYPE";
export const ADD_SELECTED_AGENT = "ADD_SELECTED_AGENT";

export const ADD_ADDRESS = "ADD_ADDRESS";
export const REMOVE_ADDRESS = "REMOVE_ADDRESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const CLEAR_ALL_ADDRESS = "CLEAR_ALL_ADDRESS";

export const ADD_CONTAINER_CART = "ADD_CONTAINER_CART";
export const REMOVE_CONTAINER_CART = "REMOVE_CONTAINER_CART";
export const UPDATE_CONTAINER_CART = "UPDATE_CONTAINER_CART";
export const REMOVE_ALL_CONTAINERS = "REMOVE_ALL_CONTAINERS";

export const ADD_DECLARATION_CART = "ADD_DECLARATION_CART";
export const REMOVE_DECLARATION_CART = "REMOVE_DECLARATION_CART";
export const REMOVE_ALL_DECLARATIONS = "REMOVE_ALL_DECLARATIONS";

export const ADD_TRUCK = "ADD_TRUCK";
export const REMOVE_TRUCK = "REMOVE_TRUCK";
export const UPDATE_TRUCK = "UPDATE_TRUCK";
export const REMOVE_ALL_TRUCK = "REMOVE_ALL_TRUCK";
export const UPDATE_SAMAYAM_TRUCK = "UPDATE_SAMAYAM_TRUCK";

export const ADD_TO_BOOK_TRUCK = "ADD_TO_BOOK_TRUCK";
export const BOOK_TRUCK_UPDATE_ADDRESS = "BOOK_TRUCK_UPDATE_ADDRESS";
export const BOOK_TRUCK_SINGLE_LOCATION = "BOOK_TRUCK_SINGLE_LOCATION";
export const BOOK_TRUCK_UPDATE_OTHER_DATA = "BOOK_TRUCK_UPDATE_OTHER_DATA";
export const BOOK_TRUCK_CLEAR = "BOOK_TRUCK_CLEAR";
export const BOOK_TRUCK_UPDATE_COMMON_DATA = "BOOK_TRUCK_UPDATE_COMMON_DATA";
export const REMOVE_CONTAINER_TRUCK_BOOK = "REMOVE_CONTAINER_TRUCK_BOOK";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const UPDATE_CONTAINER_IN_CART = "UPDATE_CONTAINER_IN_CART";
export const UPDATE_BOE_IN_CART = "UPDATE_BOE_IN_CART";
export const UPDATE_VARIABLE = "UPDATE_VARIABLE";
export const CLEAR_CART = "CLEAR_CART";
