export const decla = {
  size: 10,
  totalElements: 5,
  pageNumber: 0,
  elements: [
    {
      referenceNumber: "boe3010",
      consigneeDetails: "abc company-43",
      noOfContainers: 3,
      deliveryOrderValidity: "31/10/2020",
      status: "New",
      containerList: [
        {
          iso_code: "2000",
          container_number: "c301002",
          deliveryOrderValidity: "31/10/2020",
          boeNumber: "boe3010",
          dpwTransactionId: "T-0000000266",
          checked: false,
          storagePaidTill: "28/11/2020",
          holdAuthority: "lopsu",
          consigneeCode: "43",
          status: "NEW",
          creationDate: 1603868759390,
          pickupLocation: "T1",
          selected: false,
        },
        {
          iso_code: "4000",
          container_number: "c301003",
          deliveryOrderValidity: "31/10/2020",
          boeNumber: "boe3010",
          dpwTransactionId: "T-0000000266",
          checked: false,
          storagePaidTill: "28/11/2020",
          holdAuthority: "lopsu",
          consigneeCode: "43",
          status: "NEW",
          creationDate: 1603868759387,
          pickupLocation: "T1",
          selected: false,
        },
        {
          iso_code: "2000",
          container_number: "c301001",
          deliveryOrderValidity: "31/10/2020",
          boeNumber: "boe3010",
          dpwTransactionId: "T-0000000266",
          checked: false,
          storagePaidTill: "28/11/2020",
          holdAuthority: "lopsu",
          consigneeCode: "43",
          status: "NEW",
          creationDate: 1603868759389,
          pickupLocation: "T1",
          selected: false,
        },
      ],
      checked: false,
      openCollapsePanel: false,
      consigneeCode: null,
      creationDate: 1603868759385,
    },
    {
      referenceNumber: "boe0111",
      consigneeDetails: "abc1 company-44",
      noOfContainers: 3,
      deliveryOrderValidity: "27/11/2020",
      status: "New",
      containerList: [
        {
          iso_code: "4000",
          container_number: "c011103",
          deliveryOrderValidity: "27/11/2020",
          boeNumber: "boe0111",
          dpwTransactionId: "T-0000000266",
          checked: false,
          storagePaidTill: "28/11/2020",
          holdAuthority: "lopsu",
          consigneeCode: "44",
          status: "NEW",
          creationDate: 1603868759378,
          pickupLocation: "T1",
          selected: false,
        },
        {
          iso_code: "2000",
          container_number: "c011101",
          deliveryOrderValidity: "27/11/2020",
          boeNumber: "boe0111",
          dpwTransactionId: "T-0000000266",
          checked: false,
          storagePaidTill: "28/11/2020",
          holdAuthority: "lopsu",
          consigneeCode: "44",
          status: "NEW",
          creationDate: 1603868759382,
          pickupLocation: "T1",
          selected: false,
        },
        {
          iso_code: "2000",
          container_number: "c011102",
          deliveryOrderValidity: "27/11/2020",
          boeNumber: "boe0111",
          dpwTransactionId: "T-0000000266",
          checked: false,
          storagePaidTill: "28/11/2020",
          holdAuthority: "lopsu",
          consigneeCode: "44",
          status: "NEW",
          creationDate: 1603868759384,
          pickupLocation: "T1",
          selected: false,
        },
      ],
      checked: false,
      openCollapsePanel: false,
      consigneeCode: null,
      creationDate: 1603868759373,
    },
    {
      referenceNumber: "boe3110",
      consigneeDetails: "abc1 company-44",
      noOfContainers: 3,
      deliveryOrderValidity: "30/10/2020",
      status: "New",
      containerList: [
        {
          iso_code: "2000",
          container_number: "c311002",
          deliveryOrderValidity: "30/10/2020",
          boeNumber: "boe3110",
          dpwTransactionId: "T-0000000266",
          checked: false,
          storagePaidTill: "28/11/2020",
          holdAuthority: "lopsu",
          consigneeCode: "44",
          status: "NEW",
          creationDate: 1603868759372,
          pickupLocation: "T1",
          selected: false,
        },
        {
          iso_code: "2000",
          container_number: "c311001",
          deliveryOrderValidity: "30/10/2020",
          boeNumber: "boe3110",
          dpwTransactionId: "T-0000000266",
          checked: false,
          storagePaidTill: "28/11/2020",
          holdAuthority: "lopsu",
          consigneeCode: "44",
          status: "NEW",
          creationDate: 1603868759371,
          pickupLocation: "T1",
          selected: false,
        },
        {
          iso_code: "4000",
          container_number: "c311003",
          deliveryOrderValidity: "30/10/2020",
          boeNumber: "boe3110",
          dpwTransactionId: "T-0000000266",
          checked: false,
          storagePaidTill: "28/11/2020",
          holdAuthority: "lopsu",
          consigneeCode: "44",
          status: "NEW",
          creationDate: 1603868759367,
          pickupLocation: "T1",
          selected: false,
        },
      ],
      checked: false,
      openCollapsePanel: false,
      consigneeCode: null,
      creationDate: 1603868759360,
    },
    {
      referenceNumber: "boe6670",
      consigneeDetails: "abc company-abc",
      noOfContainers: 3,
      deliveryOrderValidity: "30/11/2020",
      status: "New",
      containerList: [
        {
          iso_code: "2000",
          container_number: "c66675",
          deliveryOrderValidity: "30/11/2020",
          boeNumber: "boe6670",
          dpwTransactionId: "T-0000000262",
          checked: false,
          storagePaidTill: "28/11/2020",
          holdAuthority: "lopsu",
          consigneeCode: "abc",
          status: "NEW",
          creationDate: 1603783964318,
          pickupLocation: "T1",
          selected: false,
        },
        {
          iso_code: "3000",
          container_number: "c66676",
          deliveryOrderValidity: "30/11/2020",
          boeNumber: "boe6670",
          dpwTransactionId: "T-0000000262",
          checked: false,
          storagePaidTill: "28/11/2020",
          holdAuthority: "lopsu",
          consigneeCode: "abc",
          status: "NEW",
          creationDate: 1603783964314,
          pickupLocation: "T1",
          selected: false,
        },
        {
          iso_code: "4000",
          container_number: "c66678",
          deliveryOrderValidity: "30/11/2020",
          boeNumber: "boe6670",
          dpwTransactionId: "T-0000000262",
          checked: false,
          storagePaidTill: "28/11/2020",
          holdAuthority: "lopsu",
          consigneeCode: "abc",
          status: "NEW",
          creationDate: 1603783964317,
          pickupLocation: "T1",
          selected: false,
        },
      ],
      checked: false,
      openCollapsePanel: false,
      consigneeCode: null,
      creationDate: 1603783964306,
    },
    {
      referenceNumber: "boe2710",
      consigneeDetails: "abc company-43",
      noOfContainers: 1,
      deliveryOrderValidity: "21/10/2020",
      status: "Expired",
      containerList: [
        {
          iso_code: "2000",
          container_number: "c271001",
          deliveryOrderValidity: "21/10/2020",
          boeNumber: "boe2710",
          dpwTransactionId: "T-0000000261",
          checked: false,
          storagePaidTill: "28/11/2020",
          holdAuthority: "lopsu",
          consigneeCode: "43",
          status: "EXP",
          creationDate: 1603777917024,
          pickupLocation: "T1",
          selected: false,
        },
      ],
      checked: false,
      openCollapsePanel: false,
      consigneeCode: null,
      creationDate: 1603777917019,
    },
  ],
  count: {
    allCount: 13,
    todayCount: 9,
    allExpiredCount: 1,
    todayExpiredCount: 0,
  },
};

export const containerList = [
  {
    iso_code: "2000",
    container_number: "c66601",
    refStatus: null,
    deliveryOrderValidity: "29/10/2020",
    boeNumber: "boe6660",
    dpwTransactionId: "T-0000000225",
    checked: false,
    storagePaidTill: "23/10/2021",
    holdAuthority: "Lorum",
  },
  {
    iso_code: "4000",
    container_number: "c66603",
    refStatus: null,
    deliveryOrderValidity: "29/10/2020",
    boeNumber: "boe6660",
    dpwTransactionId: "T-0000000225",
    checked: false,
    storagePaidTill: "23/10/2021",
    holdAuthority: "Lorum",
  },
  {
    iso_code: "2000",
    container_number: "c66602",
    refStatus: null,
    deliveryOrderValidity: "29/10/2020",
    boeNumber: "boe6660",
    dpwTransactionId: "T-0000000225",
    checked: false,
    storagePaidTill: "23/10/2021",
    holdAuthority: "Lorum",
  },
];

export const reviewdata = {
  status: "success",
  data: {
    dataItems: [
      {
        totalContainers: 1,
        subTotal: 200.0,
        deliveryCharge: 20.0,
        tax: 10.0,
        totalAmount: 230.0,
        containerSummary: [
          {
            noOfContainers: "1",
            truckType: "sdas",
            dropAddress: "Dubai",
            contactName: "sony",
            mobileNumber: "1141254",
            dateAndTime: "2020-11-20T00:54",
            containerInfo: [
              {
                iso_code: "2000",
                container_number: "c66675",
                boeNumber: "boe6670",
                requestDetailsNumber: null,
                refVehicleTypeCode: "sdas",
                dpwTransactionId: "T-0000000262",
                consigneeName: "sony",
                consigneeCode: "abc",
                consigneeNumber: "1141254",
                refStatus: null,
                consigneeEmail: "sony.sony@xyz.ae",
                dropAddress: "Dubai",
                locationCode: "123",
                pickupLocation: "T1",
                dropZone: "JAFZAS",
                date_time: "2020-11-20T00:54",
                amount: null,
                bookingDate: null,
                tariff: 200.0,
                summaryRefNo: 1064,
                isoType: null,
                truckType: null,
                truckWeight: null,
                timeInterval: null,
                consigneeDetails: null,
                truckNumber: null,
              },
            ],
            dropZone: "JAFZAS",
            pickUpZone: null,
            summaryRefNo: 1064,
          },
        ],
        containerList: [
          {
            iso_code: "2000",
            container_number: "c66675",
            boeNumber: "boe6670",
            requestDetailsNumber: null,
            refVehicleTypeCode: "sdas",
            dpwTransactionId: "T-0000000262",
            consigneeName: "sony",
            consigneeCode: "abc",
            consigneeNumber: "1141254",
            refStatus: null,
            consigneeEmail: "sony.sony@xyz.ae",
            dropAddress: "Dubai",
            locationCode: "123",
            pickupLocation: "T1",
            dropZone: "JAFZAS",
            date_time: "2020-11-20T00:54",
            amount: null,
            bookingDate: null,
            tariff: 200.0,
            summaryRefNo: 1064,
            isoType: null,
            truckType: null,
            truckWeight: null,
            timeInterval: null,
            consigneeDetails: null,
            truckNumber: null,
          },
        ],
      },
    ],
  },
  message: "",
  code: "",
};

export const bookingDetails = {
  size: 5,
  totalElements: 37,
  pageNumber: 0,
  elements: [
    {
      bookingNumber: "LM000759",
      createdOn: "27/12/2020",
      amountPaid: "230.0",
      containersInYard: 1,
      consigneeDetails: null,
      containersConfirmed: 0,
      containersBooked: 1,
      containersToTown: 0,
      containersDelivered: 0,
      emptyContainersDelivered: 0,
      dropLocation: null,
      containerList: [
        {
          container_number: "cm06006",
          boeNumber: "boem006",
          requestDetailsNumber: "LM000759",
          dpwTransactionId: "T-0000000535",
          consigneeContactName: "Sheikh",
          consigneeContactNumber: "2314567897",
          refStatus: {
            code: "PEND",
            refStatusLocales: {
              name: "Pending",
              description: "Pending",
              locale: null,
            },
          },
          dropAddress: "E66 - Nad Al Sheba - Dubai - United Arab Emirates",
          pickupLocation: "T2",
          dropZone: "JAFZAS",
          bookingDate: "27/12/2020 10:59",
          tariff: 200.0,
          summaryRefNo: 0,
          consigneeDetails: "abc company-abc",
          containerTrackList: [],
          phoneNumber: "2345678901",
          addressLine1: "Nad Al sheba",
        },
      ],
      dateAndTime: null,
      multiLocFlag: "N",
      statusCode: "FPAY",
      truckList: [
        {
          vehicleCode: "sdas",
          vehicleName: "asda",
          dateAndTime: "27/12/2020 10:58",
          interval: "00:30",
        },
      ],
    },
    {
      bookingNumber: "LM000777",
      createdOn: "27/12/2020",
      amountPaid: "230.0",
      containersInYard: 1,
      consigneeDetails: null,
      containersConfirmed: 0,
      containersBooked: 1,
      containersToTown: 0,
      containersDelivered: 0,
      emptyContainersDelivered: 0,
      dropLocation: null,
      containerList: [
        {
          container_number: "cm06017",
          boeNumber: "boem006",
          requestDetailsNumber: "LM000777",
          dpwTransactionId: "T-0000000536",
          consigneeContactName: "Sheikh",
          consigneeContactNumber: "2314567897",
          refStatus: {
            code: "PEND",
            refStatusLocales: {
              name: "Pending",
              description: "Pending",
              locale: null,
            },
          },
          dropAddress: "E66 - Nad Al Sheba - Dubai - United Arab Emirates",
          pickupLocation: "T2",
          dropZone: "JAFZAS",
          bookingDate: "27/12/2020 12:59",
          tariff: 200.0,
          summaryRefNo: 0,
          consigneeDetails: "abc company-abc",
          containerTrackList: [],
          phoneNumber: "2345678901",
          addressLine1: "Nad Al sheba",
        },
      ],
      dateAndTime: null,
      multiLocFlag: "N",
      statusCode: "FPAY",
      truckList: [
        {
          vehicleCode: "SEP1309",
          vehicleName: "SEP13112",
          dateAndTime: "27/12/2020 12:52",
          interval: "00:20",
        },
      ],
    },
    {
      bookingNumber: "LM000756",
      createdOn: "27/12/2020",
      amountPaid: "230.0",
      containersInYard: 1,
      consigneeDetails: null,
      containersConfirmed: 0,
      containersBooked: 1,
      containersToTown: 0,
      containersDelivered: 0,
      emptyContainersDelivered: 0,
      dropLocation: null,
      containerList: [
        {
          container_number: "cm06010",
          boeNumber: "boem006",
          requestDetailsNumber: "LM000756",
          dpwTransactionId: "T-0000000535",
          consigneeContactName: "Sheikh",
          consigneeContactNumber: "2314567897",
          refStatus: {
            code: "PEND",
            refStatusLocales: {
              name: "Pending",
              description: "Pending",
              locale: null,
            },
          },
          dropAddress: "E66 - Nad Al Sheba - Dubai - United Arab Emirates",
          pickupLocation: "T2",
          dropZone: "JAFZAS",
          bookingDate: "27/12/2020 10:42",
          tariff: 200.0,
          summaryRefNo: 0,
          consigneeDetails: "abc company-abc",
          containerTrackList: [],
          phoneNumber: "2345678901",
          addressLine1: "Nad Al sheba",
        },
      ],
      dateAndTime: null,
      multiLocFlag: "N",
      statusCode: "SUCC",
      truckList: [
        {
          vehicleCode: "sdfsdf",
          vehicleName: "hhgjgh",
          dateAndTime: "27/12/2020 10:41",
          interval: "00:40",
        },
      ],
    },
    {
      bookingNumber: "LM000778",
      createdOn: "27/12/2020",
      amountPaid: "230.0",
      containersInYard: 1,
      consigneeDetails: null,
      containersConfirmed: 0,
      containersBooked: 1,
      containersToTown: 0,
      containersDelivered: 0,
      emptyContainersDelivered: 0,
      dropLocation: null,
      containerList: [
        {
          container_number: "cm06014",
          boeNumber: "boem006",
          requestDetailsNumber: "LM000778",
          dpwTransactionId: "T-0000000536",
          consigneeContactName: "Sheikh",
          consigneeContactNumber: "2314567897",
          refStatus: {
            code: "PEND",
            refStatusLocales: {
              name: "Pending",
              description: "Pending",
              locale: null,
            },
          },
          dropAddress: "E66 - Nad Al Sheba - Dubai - United Arab Emirates",
          pickupLocation: "T2",
          dropZone: "JAFZAS",
          bookingDate: "27/12/2020 13:02",
          tariff: 200.0,
          summaryRefNo: 0,
          consigneeDetails: "abc company-abc",
          containerTrackList: [],
          phoneNumber: "2345678901",
          addressLine1: "Nad Al sheba",
        },
      ],
      dateAndTime: null,
      multiLocFlag: "N",
      statusCode: "SUCC",
      truckList: [
        {
          vehicleCode: "SEP1309",
          vehicleName: "SEP13112",
          dateAndTime: "27/12/2020 12:52",
          interval: "00:20",
        },
      ],
    },
    {
      bookingNumber: "LM000757",
      createdOn: "27/12/2020",
      amountPaid: "230.0",
      containersInYard: 1,
      consigneeDetails: null,
      containersConfirmed: 0,
      containersBooked: 1,
      containersToTown: 0,
      containersDelivered: 0,
      emptyContainersDelivered: 0,
      dropLocation: null,
      containerList: [
        {
          container_number: "cm06005",
          boeNumber: "boem006",
          requestDetailsNumber: "LM000757",
          dpwTransactionId: "T-0000000535",
          consigneeContactName: "Sheikh",
          consigneeContactNumber: "2314567897",
          refStatus: {
            code: "PEND",
            refStatusLocales: {
              name: "Pending",
              description: "Pending",
              locale: null,
            },
          },
          dropAddress: "E66 - Nad Al Sheba - Dubai - United Arab Emirates",
          pickupLocation: "T2",
          dropZone: "JAFZAS",
          bookingDate: "27/12/2020 10:49",
          tariff: 200.0,
          summaryRefNo: 0,
          consigneeDetails: "abc company-abc",
          containerTrackList: [],
          phoneNumber: "2345678901",
          addressLine1: "Nad Al sheba",
        },
      ],
      dateAndTime: null,
      multiLocFlag: "N",
      statusCode: "SUCC",
      truckList: [
        {
          vehicleCode: "SEP1309",
          vehicleName: "SEP13112",
          dateAndTime: "27/12/2020 10:47",
          interval: "00:20",
        },
      ],
    },
  ],
  count: null,
};

export const trackData = [
  {
    status: "PTOK",
    actionDateAndTime: "29/12/2020 11:01",
    containerList: null,
    createdBy: "ABC",
  },
  {
    status: "CONF",
    actionDateAndTime: "30/12/2020 02:30",
    containerList: null,
    createdBy: "DEF",
  },
  {
    status: "INPRO",
    actionDateAndTime: "29/12/2020 11:01",
    containerList: null,
    createdBy: "XYZ",
  },
  {
    status: "PODUPL",
    actionDateAndTime: "29/12/2020 11:01",
    containerList: null,
    createdBy: "LMN",
  },
  {
    status: "FCL_DEL",
    actionDateAndTime: "29/12/2020 11:01",
    containerList: null,
    createdBy: "QPS",
  },
];
export const addressData = [
  {
    consigneeContactName: "Dubai Trade",
    consigneeContactNumber: "+971098765432",
    phoneNumber: "+97123456789",
    addressLine1: "xyz",
    dropAddress:
      "30 15 Street - Za'abeelZa'abeel 2 - Dubai - United Arab Emirates",
    code: "301",
    locationCode: "301",
    dpwCompanyCode: "I-S0006",
    isActive: null,
    dropZone: null,
    selectedDropZone: "JAFZAN",
    addressNickname: "jabel Ali jafza",
  },
  {
    consigneeContactName: "Merine",
    consigneeContactNumber: "525665078",
    phoneNumber: "99887762",
    addressLine1: "qweqwewqe",
    dropAddress:
      "Office No: 907 and 908, 9th Floor, JAFZA ONE - Tower A, PO Box 61398 - جبل عليمنطقة جبل علي الحرة - دبي - United Arab Emirates",
    code: "261",
    locationCode: "261",
    dpwCompanyCode: "I-S0006",
    isActive: null,
    dropZone: null,
    selectedDropZone: "JAFZAS",
    addressNickname: "Marina",
  },
  {
    consigneeContactName: "contact1",
    consigneeContactNumber: "+971333333333",
    phoneNumber: "+97132112122",
    addressLine1: "121212",
    dropAddress:
      "541st St - Mina Jebel AliJebel Ali Freezone - Dubai - United Arab Emirates",
    code: "262",
    locationCode: "262",
    dpwCompanyCode: "I-S0006",
    isActive: null,
    dropZone: null,
    selectedDropZone: "JAFZAS",
    addressNickname: "Tseting11",
  },
  {
    consigneeContactName: "Sheikh",
    consigneeContactNumber: "+971999998888",
    phoneNumber: "+97111222222",
    addressLine1: "Dubai Land",
    dropAddress:
      "Office No: 907 and 908, 9th Floor, JAFZA ONE - Tower A, PO Box 61398 - جبل عليمنطقة جبل علي الحرة - دبي - United Arab Emirates",
    code: "263",
    locationCode: "263",
    dpwCompanyCode: "I-S0006",
    isActive: null,
    dropZone: null,
    selectedDropZone: "JAFZAS",
    addressNickname: "Dubai Land",
  },
  {
    consigneeContactName: "King",
    consigneeContactNumber: "+971123456789",
    phoneNumber: "+9719876543",
    addressLine1: "qwerty",
    dropAddress: "30 14 B St - Al Raffa - Dubai - United Arab Emirates",
    code: "266",
    locationCode: "266",
    dpwCompanyCode: "I-S0006",
    isActive: null,
    dropZone: null,
    selectedDropZone: "JAFZAS",
    addressNickname: "Kingi",
  },
  {
    consigneeContactName: "qweqweqew",
    consigneeContactNumber: "+9710",
    phoneNumber: "+9710",
    addressLine1: "qewqweqwe",
    dropAddress:
      "Office No: 907 and 908, 9th Floor, JAFZA ONE - Tower A, PO Box 61398 - جبل عليمنطقة جبل علي الحرة - دبي - United Arab Emirates",
    code: "281",
    locationCode: "281",
    dpwCompanyCode: "I-S0006",
    isActive: null,
    dropZone: null,
    selectedDropZone: "JAFZAN",
    addressNickname: "qweqweqwe",
  },
  {
    consigneeContactName: "contact person",
    consigneeContactNumber: "+971111111111",
    phoneNumber: "+97111111111",
    addressLine1: "AddrssLine 1",
    dropAddress:
      "Office No: 907 and 908, 9th Floor, JAFZA ONE - Tower A, PO Box 61398 - جبل عليمنطقة جبل علي الحرة - دبي - United Arab Emirates",
    code: "282",
    locationCode: "282",
    dpwCompanyCode: "I-S0006",
    isActive: null,
    dropZone: null,
    selectedDropZone: "JAFZAS",
    addressNickname: "Nickname",
  },
  {
    consigneeContactName: "chhaya",
    consigneeContactNumber: "+971555555555",
    phoneNumber: "+97158583275",
    addressLine1: "discovery",
    dropAddress: "E11 - Mina Jebel Ali - Dubai - United Arab Emirates",
    code: "341",
    locationCode: "341",
    dpwCompanyCode: "I-S0006",
    isActive: null,
    dropZone: null,
    selectedDropZone: "JAFZAN",
    addressNickname: "chhaya",
  },
  {
    consigneeContactName: "bella",
    consigneeContactNumber: "+971098765432",
    phoneNumber: "+97134534534",
    addressLine1: "Bachu",
    dropAddress: "Unnamed Road - Dubai - United Arab Emirates",
    code: "321",
    locationCode: "321",
    dpwCompanyCode: "I-S0006",
    isActive: null,
    dropZone: null,
    selectedDropZone: "JAFZAN",
    addressNickname: "bobby",
  },
  {
    consigneeContactName: "azi",
    consigneeContactNumber: "+971987654565",
    phoneNumber: "+97198765432",
    addressLine1: "address line test",
    dropAddress:
      "Unnamed Road - Dubai Design District - Dubai - United Arab Emirates",
    code: "322",
    locationCode: "322",
    dpwCompanyCode: "I-S0006",
    isActive: null,
    dropZone: null,
    selectedDropZone: "JAFZAS",
    addressNickname: "test urgent",
  },
  {
    consigneeContactName: "admin",
    consigneeContactNumber: "123123123",
    phoneNumber: "234234243",
    addressLine1: "Near gate number 2",
    dropAddress: "1600 Amphitheatre Pkwy, Mountain View, CA 94043, USA",
    code: "242",
    locationCode: "242",
    dpwCompanyCode: "I-S0006",
    isActive: null,
    dropZone: null,
    selectedDropZone: "JAFZAS",
    addressNickname: "JAFZA1",
  },
  {
    consigneeContactName: "aabbcc",
    consigneeContactNumber: "000009997",
    phoneNumber: "11111111",
    addressLine1: "landmark text1",
    dropAddress:
      "541st St - Mina Jebel AliJebel Ali Freezone - Dubai - United Arab Emirates",
    code: "243",
    locationCode: "243",
    dpwCompanyCode: "I-S0006",
    isActive: null,
    dropZone: null,
    selectedDropZone: "JAFZAS",
    addressNickname: "abc1234",
  },
];
export const reviewBooked = [
  {
    totalContainers: 3,
    subTotal: 600.0,
    deliveryCharge: 150.0,
    tax: 30.0,
    totalAmount: 750.0,
    containerSummary: [
      {
        noOfContainers: "1",
        truckType: "sdfsdf",
        dropAddress: "E11 - Mina Jebel Ali - Dubai - United Arab Emirates",
        contactName: "chhaya",
        mobileNumber: "+971555555555",
        dateAndTime: "2021-02-25T10:31:11.048Z",
        containerInfo: [
          {
            iso_code: "2000",
            container_number: "4C04022021FIJ4",
            boeNumber: "101-04022021FIJ4-20",
            refVehicleTypeCode: "sdfsdf",
            refVehicleTypeName: "sdfsdf",
            dpwTransactionId: "T-0000000655",
            consigneeContactName: "chhaya",
            consigneeCode: "S0006",
            consigneeContactNumber: "+971555555555",
            dropAddress: "E11 - Mina Jebel Ali - Dubai - United Arab Emirates",
            locationCode: "341",
            pickupLocation: "T2",
            dropZone: "JAFZAS",
            date_time: "2021-02-25T10:31:11.048Z",
            tariff: 200.0,
            summaryRefNo: 2603,
            timeInterval: "0",
            phoneNumber: "+97158583275",
            addressLine1: "discovery",
          },
        ],
        dropZone: "JAFZAS",
        pickUpZone: null,
        summaryRefNo: 2603,
      },
      {
        noOfContainers: "2",
        truckType: "Test, SEP1309",
        dropAddress:
          "30 15 Street - Za'abeelZa'abeel 2 - Dubai - United Arab Emirates",
        contactName: "Dubai Trade",
        mobileNumber: "+971098765432",
        dateAndTime: "2021-02-25T10:31:11.048Z",
        containerInfo: [
          {
            iso_code: "2000",
            container_number: "4C04022021FIJ6",
            boeNumber: "101-04022021FIJ4-20",
            refVehicleTypeCode: "SEP1309",
            refVehicleTypeName: "SEP1309",
            dpwTransactionId: "T-0000000655",
            consigneeContactName: "Dubai Trade",
            consigneeCode: "S0006",
            consigneeContactNumber: "+971098765432",
            dropAddress:
              "30 15 Street - Za'abeelZa'abeel 2 - Dubai - United Arab Emirates",
            locationCode: "301",
            pickupLocation: "T3",
            dropZone: "JAFZAS",
            date_time: "2021-02-25T10:31:11.048Z",
            tariff: 200.0,
            summaryRefNo: 2604,
            timeInterval: "0",
            phoneNumber: "+97123456789",
            addressLine1: "xyz",
          },
          {
            iso_code: "2000",
            container_number: "4C04022021FIJ2",
            boeNumber: "101-04022021FIJ4-20",
            refVehicleTypeCode: "Test",
            refVehicleTypeName: "Test",
            dpwTransactionId: "T-0000000655",
            consigneeContactName: "Dubai Trade",
            consigneeCode: "S0006",
            consigneeContactNumber: "+971098765432",
            dropAddress:
              "30 15 Street - Za'abeelZa'abeel 2 - Dubai - United Arab Emirates",
            locationCode: "301",
            pickupLocation: "T2",
            dropZone: "JAFZAS",
            date_time: "2021-02-25T10:31:11.048Z",
            tariff: 200.0,
            summaryRefNo: 2604,
            timeInterval: "0",
            phoneNumber: "+97123456789",
            addressLine1: "xyz",
          },
        ],
        dropZone: "JAFZAS",
        pickUpZone: null,
        summaryRefNo: 2604,
      },
    ],
    containerList: [
      {
        iso_code: "2000",
        container_number: "4C04022021FIJ6",
        boeNumber: "101-04022021FIJ4-20",
        refVehicleTypeCode: "SEP1309",
        refVehicleTypeName: "SEP1309",
        dpwTransactionId: "T-0000000655",
        consigneeContactName: "Dubai Trade",
        consigneeCode: "S0006",
        consigneeContactNumber: "+971098765432",
        dropAddress:
          "30 15 Street - Za'abeelZa'abeel 2 - Dubai - United Arab Emirates",
        locationCode: "301",
        pickupLocation: "T3",
        dropZone: "JAFZAS",
        date_time: "2021-02-25T10:31:11.048Z",
        tariff: 200.0,
        summaryRefNo: 2604,
        timeInterval: "0",
        phoneNumber: "+97123456789",
        addressLine1: "xyz",
      },
      {
        iso_code: "2000",
        container_number: "4C04022021FIJ2",
        boeNumber: "101-04022021FIJ4-20",
        refVehicleTypeCode: "Test",
        refVehicleTypeName: "Test",
        dpwTransactionId: "T-0000000655",
        consigneeContactName: "Dubai Trade",
        consigneeCode: "S0006",
        consigneeContactNumber: "+971098765432",
        dropAddress:
          "30 15 Street - Za'abeelZa'abeel 2 - Dubai - United Arab Emirates",
        locationCode: "301",
        pickupLocation: "T2",
        dropZone: "JAFZAS",
        date_time: "2021-02-25T10:31:11.048Z",
        tariff: 200.0,
        summaryRefNo: 2604,
        timeInterval: "0",
        phoneNumber: "+97123456789",
        addressLine1: "xyz",
      },
      {
        iso_code: "2000",
        container_number: "4C04022021FIJ4",
        boeNumber: "101-04022021FIJ4-20",
        refVehicleTypeCode: "sdfsdf",
        refVehicleTypeName: "sdfsdf",
        dpwTransactionId: "T-0000000655",
        consigneeContactName: "chhaya",
        consigneeCode: "S0006",
        consigneeContactNumber: "+971555555555",
        dropAddress: "E11 - Mina Jebel Ali - Dubai - United Arab Emirates",
        locationCode: "341",
        pickupLocation: "T2",
        dropZone: "JAFZAS",
        date_time: "2021-02-25T10:31:11.048Z",
        tariff: 200.0,
        summaryRefNo: 2603,
        timeInterval: "0",
        phoneNumber: "+97158583275",
        addressLine1: "discovery",
      },
    ],
  },
];
/* */
export const bookTruckSampleData = {
  requestTruckType: [],
  containerList: [
    {
      iso_code: "2000",
      container_number: "c030521_1",
      boeNumber: "boe_030521",
      dpwTransactionId: "T-0000000423",
      checked: false,
      consigneeCode: "S0006",
      status: "ACTIVE",
      creationDate: "2021-05-02T09:33:54.896+00:00",
      selected: true,
    },
    {
      iso_code: "2000",
      container_number: "c030521_3",
      boeNumber: "boe_030521",
      dpwTransactionId: "T-0000000423",
      checked: false,
      consigneeCode: "S0006",
      status: "ACTIVE",
      creationDate: "2021-05-02T09:33:54.856+00:00",
      selected: true,
    },
    {
      iso_code: "2000",
      container_number: "c190521_2",
      boeNumber: "302190521",
      dpwTransactionId: "T-0000000444",
      checked: false,
      consigneeCode: "S0006",
      status: "ACTIVE",
      creationDate: "2021-05-16T07:19:34.755+00:00",
      selected: true,
    },
    {
      iso_code: "2000",
      container_number: "c190521_1",
      boeNumber: "302190521",
      dpwTransactionId: "T-0000000444",
      checked: false,
      consigneeCode: "S0006",
      status: "ACTIVE",
      creationDate: "2021-05-16T07:19:34.754+00:00",
      selected: true,
    },
  ],
  multiLocAndTime: true,
};
export const containerType = [
  { key: "generalPurpose", label: "General Purpose" },
  { key: "doubleDoor", label: "Double Door" },
  { key: "isoReefer", label: "ISO REEFER" },
  { key: "halfHeight", label: "Half Height" },
];
